---
  #- name: Update apt cache # apt-get update
  #  apt:
   #   update_cache: yes

  - name: Install required packages # apt-get install nginx -y
    apt:
      name: nginx
      install_recommends: yes

  - name: Start nginx service
    service:
      name: nginx
      state: started

 # - name: Delete default nginx site
  #  file:
   #   path: /etc/nginx/sites-enabled/default
    #  state: absent
   # notify: reload nginx

 
