---  
  - name: Copy MySQL configuration
    template: 
      src: "mysqld.cnf.j2"
      dest: "{{ mysql_server_conf }}"
      owner: "root"
      group: "root"
    notify:
      - Restart MySQL service
