---
# tasks file for php
  - name: install php
    package:
      name: "{{ item }}"
      state: installed
    with_items:
      - php
      - php-curl
      - php-gd 
      - php-mbstring 
      - php-mcrypt 
      - php-xml 
      - php-xmlrpc
      - php-mysql
      - nmap
    #notify: Restart apache service
  - template:
      src: php.ini.j2
      dest: /etc/php/7.0/cli/php.ini

